[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/flavio1110"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/flavio1110"

    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "twitter-x"
    name = "X (Twitter)"
    url = "https://twitter.com/flavio1110"

    [social.params]
        icon = "brand-x"

[[social]]
    identifier = "mailto"
    name = "Email"
    url = "mailto:flavio1110@gmail.com"

    [social.params]
        icon = "mail"
