mainSections = ["post"]
favicon = "/images/favicon.ico"
description = "I'm fascinated about how tech can change people's lives and how we can tackle real-world problems with software. Hit me up using one of the channels below, and we'll chat real soon! :)"
RSSFullContent = true

[author]
    name = "Flavio Silva"
    email = "flavio1110@gmail.com"

[sidebar]
    avatar = "img/avatar.webp"
    subtitle = "Software engineer and stuff ッ"

[footer]
    since = 2023

[colorScheme]
    toggle = true
    default = "auto"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives" },
        { type = "tag-cloud" },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = false
