pipeline:
  buid-docker: 
    image: docker:17.04.0-ce
    when:
      event: push
      branch: [master]
    privileged: true
    volumes:
      - $HOME/site:/site
    commands:
      - mkdir site
      - cp -R * /site