# General Settings
name: Flavio Silva
title: Flavio Silva
job_title: Software engineer and stuff ッ
email: flavio1110@gmail.com
description: I'm fascinated about how tech can change people's lives and how we can tackle real-world problems with software. Hit me up using one of the channels below, and we'll chat real soon! :)
avatar: https://fsilva.me/images/avatar.jpg
favicon: images/favicon.ico
twitter_handler: your_handler
analytics_code: G-77HRLY1L61
disqus: flaviosilvadev

# Social Accounts
social_networks:
  - { name: facebook, url: "" }
  - { name: twitter, url: "https://twitter.com/flavio1110" }
  - { name: instagram, url: "" }
  - { name: google-plus, url: "" }
  - { name: linkedin, url: "https://www.linkedin.com/in/flavio1110" }
  - { name: skype, url: "" }
  - { name: github, url: "https://github.com/flavio1110" }
  - { name: codepen, url: "" }
  - { name: stack-overflow, url: "" }
  - { name: dribbble, url: "" }
  - { name: behance, url: "" }
  - { name: pinterest, url: "" }
  - { name: tumblr, url: "" }
  - { name: youtube, url: "" }
  - { name: vimeo, url: "" }
  - { name: vine, url: "" }
  - { name: 500px, url: "" }
  - { name: flickr, url: "" }
  - { name: spotify, url: "" }
  - { name: steam, url: "" }
  - { name: wordpress, url: "" }
  - { name: xing, url: "" }
  - { name: bitcoin, url: "" }
  - { name: pocket, url: "" }
  - { name: applemusic, url: "" }

# Modules Settings
show_categories: 0
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: "false"

# Serving
url: "https://fsilva.me"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Tags
tag_page_layout: tag_index
tag_page_dir: tag

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown

excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      bold_every: 5
